name: governance-kyc-psc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - geopandas
  - contextily
  - numpy
  - python-dotenv
  - pandas
  - tqdm
  - matplotlib
  - seaborn
  - pgeocode
  - pyarrow
  - pip
  - pip:
    - neo4j
    - neo4j-viz
    - playwright
    - pyspark==3.5.1
    - pydeck
    - pydeck-carto
